### ISSUE TITLE
TypeError escapes the runtime

### ISSUE THREAD

**Issue by qlonik** [Matechs-Garage/matechs-effect#282]
When I'm writing code like this, the error is not caught by effect runtime. The error is being thrown by node process and program exits with code 1.

```typescript
import { effect as T, either } from "@matechs/core";
import { pipe } from "@matechs/core/Function";

const sampleAsync = T.async<Error, void>((next) => {
  const t = setTimeout(() => {
    next(either.right(undefined));
  }, 100);

  return (cb) => {
    clearTimeout(t);
    cb();
  };
});

pipe(
  T.pure<string[]>([]),
  T.chain((data) =>
    pipe(
      sampleAsync,
      T.map(() => data[0].length)
    )
  ),
  T.runToPromiseExit,
  (x) => x.then(console.log)
);
```

Here is the exit stack trace:
```
node.exe ts-node\dist\bin.js trying.ts

trying.ts:20
      T.map(() => data[0].length)
                          ^
TypeError: Cannot read property 'length' of undefined
    at MapFrame.f (trying.ts:20:27)
    at DriverImpl.next (node_modules\@matechs\core\Support\Driver\driver\index.js:196:41)
    at DriverImpl.foldResume (node_modules\@matechs\core\Support\Driver\driver\index.js:206:27)
    at RuntimeImpl.run (node_modules\@matechs\core\Support\Runtime\index.js:18:20)
    at RuntimeImpl.dispatch (node_modules\@matechs\core\Support\Runtime\index.js:26:18)
    at DriverImpl.resume (node_modules\@matechs\core\Support\Driver\driver\index.js:220:34)
    at node_modules\@matechs\core\Support\Driver\driver\index.js:230:19
    at Timeout._onTimeout (trying.ts:6:5)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

Process finished with exit code 1
```

Note, when I change `sampleAsync` in main pipe with `T.unit`, the error is correctly caught by the runtime.

**Comment by mikearnaldi** [comment]
Fixed in #285
